//! `alacritty_renderer` — alacritty's GLES2/GLSL3 cell renderer, extracted as a
//! standalone library for embedding (fressh / react-native-terminal).
//!
//! This crate `#[path]`-includes the upstream renderer draw code
//! (`../alacritty/src/renderer/`) and provides MINIMAL shims for the few support
//! types it pulls from the binary crate (`crate::gl`, `crate::display::*`,
//! `crate::config::*`), so it builds WITHOUT the binary crate's
//! config/window/winit/glutin/serde machinery. The shims reproduce only what the
//! renderer reads — see docs §6 "Measured cut-line".
//!
//! The only edits to upstream `renderer/mod.rs` are the context seam
//! (`Renderer::new` takes `(get_proc_address, is_gles)` instead of a glutin
//! context) and dropping `pub mod platform;`.

/// OpenGL bindings (generated by build.rs via gl_generator), at the path the
/// renderer expects: `crate::gl`.
#[allow(
	clippy::all,
	non_upper_case_globals,
	non_camel_case_types,
	non_snake_case,
	unused,
	unsafe_op_in_unsafe_fn
)]
pub mod gl {
	include!(concat!(env!("OUT_DIR"), "/gl_bindings.rs"));
}

/// Minimal config shims (the renderer uses only a few small value types).
pub mod config {
	pub mod ui_config {
		/// `crate::config::ui_config::Delta` — character/glyph offset.
		#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
		pub struct Delta<T: Default> {
			pub x: T,
			pub y: T,
		}
	}

	pub mod debug {
		/// `crate::config::debug::RendererPreference` — force a backend.
		#[derive(Debug, Clone, Copy, PartialEq, Eq)]
		pub enum RendererPreference {
			Glsl3,
			Gles2,
			Gles2Pure,
		}
	}

	pub mod font {
		use crossfont::Size as FontSize;

		use crate::config::ui_config::Delta;

		/// `crate::config::font::Font` — copied from alacritty's config/font.rs,
		/// minus serde/config-derive and the removed `use_thin_strokes` field.
		#[derive(Debug, Clone, PartialEq)]
		pub struct Font {
			pub offset: Delta<i8>,
			pub glyph_offset: Delta<i8>,
			normal: FontDescription,
			bold: SecondaryFontDescription,
			italic: SecondaryFontDescription,
			bold_italic: SecondaryFontDescription,
			size: Size,
			pub builtin_box_drawing: bool,
		}

		impl Font {
			/// Build a font from a single font-file path + point size. (fressh)
			///
			/// On platforms without font discovery (Android/iOS, via the fressh
			/// crossfont fork's direct backend) the family string is treated as a
			/// font file path. All styles fall back to this one file.
			pub fn from_path(path: impl Into<String>, size_pt: f32) -> Font {
				Font {
					normal: FontDescription { family: path.into(), style: None },
					size: Size(FontSize::new(size_pt)),
					..Font::default()
				}
			}

			pub fn with_size(self, size: FontSize) -> Font {
				Font { size: Size(size), ..self }
			}

			#[inline]
			pub fn size(&self) -> FontSize {
				self.size.0
			}

			pub fn normal(&self) -> &FontDescription {
				&self.normal
			}

			pub fn bold(&self) -> FontDescription {
				self.bold.desc(&self.normal)
			}

			pub fn italic(&self) -> FontDescription {
				self.italic.desc(&self.normal)
			}

			pub fn bold_italic(&self) -> FontDescription {
				self.bold_italic.desc(&self.normal)
			}
		}

		impl Default for Font {
			fn default() -> Font {
				Self {
					builtin_box_drawing: true,
					glyph_offset: Default::default(),
					bold_italic: Default::default(),
					italic: Default::default(),
					offset: Default::default(),
					normal: Default::default(),
					bold: Default::default(),
					size: Default::default(),
				}
			}
		}

		#[derive(Debug, Clone, PartialEq)]
		pub struct FontDescription {
			pub family: String,
			pub style: Option<String>,
		}

		impl Default for FontDescription {
			fn default() -> FontDescription {
				FontDescription {
					#[cfg(not(any(target_os = "macos", windows)))]
					family: "monospace".into(),
					#[cfg(target_os = "macos")]
					family: "Menlo".into(),
					#[cfg(windows)]
					family: "Consolas".into(),
					style: None,
				}
			}
		}

		#[derive(Debug, Default, Clone, PartialEq)]
		pub struct SecondaryFontDescription {
			family: Option<String>,
			style: Option<String>,
		}

		impl SecondaryFontDescription {
			pub fn desc(&self, fallback: &FontDescription) -> FontDescription {
				FontDescription {
					family: self.family.clone().unwrap_or_else(|| fallback.family.clone()),
					style: self.style.clone(),
				}
			}
		}

		#[derive(Debug, Clone, PartialEq)]
		struct Size(FontSize);

		impl Default for Size {
			fn default() -> Self {
				Self(FontSize::new(11.25))
			}
		}
	}
}

/// Minimal display shims.
pub mod display {
	use std::cmp;

	use alacritty_terminal::term::{MIN_COLUMNS, MIN_SCREEN_LINES};

	/// `crate::display::SizeInfo` — copied from alacritty's display/mod.rs
	/// (struct + the getters/constructor the renderer uses).
	#[derive(Debug, Copy, Clone)]
	pub struct SizeInfo<T = f32> {
		width: T,
		height: T,
		cell_width: T,
		cell_height: T,
		padding_x: T,
		padding_y: T,
		screen_lines: usize,
		columns: usize,
	}

	impl<T: Clone + Copy> SizeInfo<T> {
		#[inline]
		pub fn width(&self) -> T {
			self.width
		}

		#[inline]
		pub fn height(&self) -> T {
			self.height
		}

		#[inline]
		pub fn cell_width(&self) -> T {
			self.cell_width
		}

		#[inline]
		pub fn cell_height(&self) -> T {
			self.cell_height
		}

		#[inline]
		pub fn padding_x(&self) -> T {
			self.padding_x
		}

		#[inline]
		pub fn padding_y(&self) -> T {
			self.padding_y
		}
	}

	// `last_column()`/`last_line()` etc. used by rects.rs come from this trait's
	// default methods. Copied from alacritty's `impl TermDimensions for SizeInfo`.
	impl alacritty_terminal::grid::Dimensions for SizeInfo {
		#[inline]
		fn columns(&self) -> usize {
			self.columns
		}

		#[inline]
		fn screen_lines(&self) -> usize {
			self.screen_lines
		}

		#[inline]
		fn total_lines(&self) -> usize {
			self.screen_lines
		}
	}

	impl SizeInfo<f32> {
		#[allow(clippy::too_many_arguments)]
		pub fn new(
			width: f32,
			height: f32,
			cell_width: f32,
			cell_height: f32,
			mut padding_x: f32,
			mut padding_y: f32,
			dynamic_padding: bool,
		) -> SizeInfo {
			if dynamic_padding {
				padding_x = Self::dynamic_padding(padding_x.floor(), width, cell_width);
				padding_y = Self::dynamic_padding(padding_y.floor(), height, cell_height);
			}

			let lines = (height - 2. * padding_y) / cell_height;
			let screen_lines = cmp::max(lines as usize, MIN_SCREEN_LINES);

			let columns = (width - 2. * padding_x) / cell_width;
			let columns = cmp::max(columns as usize, MIN_COLUMNS);

			SizeInfo {
				width,
				height,
				cell_width,
				cell_height,
				padding_x: padding_x.floor(),
				padding_y: padding_y.floor(),
				screen_lines,
				columns,
			}
		}

		#[inline]
		pub fn reserve_lines(&mut self, count: usize) {
			self.screen_lines = cmp::max(self.screen_lines.saturating_sub(count), MIN_SCREEN_LINES);
		}

		#[inline]
		fn dynamic_padding(padding: f32, dimension: f32, cell_dimension: f32) -> f32 {
			padding + ((dimension - 2. * padding) % cell_dimension) / 2.
		}
	}

	pub mod color {
		use alacritty_terminal::vte::ansi::Rgb as VteRgb;

		/// `crate::display::color::Rgb` — newtype over the engine's VTE Rgb.
		#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
		pub struct Rgb(pub VteRgb);

		impl Rgb {
			#[inline]
			pub const fn new(r: u8, g: u8, b: u8) -> Self {
				Self(VteRgb { r, g, b })
			}

			#[inline]
			pub fn as_tuple(self) -> (u8, u8, u8) {
				(self.0.r, self.0.g, self.0.b)
			}
		}

		impl std::ops::Deref for Rgb {
			type Target = VteRgb;

			fn deref(&self) -> &VteRgb {
				&self.0
			}
		}
	}

	pub mod content {
		use alacritty_terminal::index::Point;
		use alacritty_terminal::term::cell::{Flags, Hyperlink};

		use super::color::Rgb;

		/// `crate::display::content::RenderableCell` — the cell the renderer
		/// draws. We OWN this (and its producer); alacritty's producer is tangled
		/// with config/Display/hints/search (docs §6).
		#[derive(Clone, Debug)]
		pub struct RenderableCell {
			pub character: char,
			pub point: Point<usize>,
			pub fg: Rgb,
			pub bg: Rgb,
			pub bg_alpha: f32,
			pub underline: Rgb,
			pub flags: Flags,
			pub extra: Option<Box<RenderableCellExtra>>,
		}

		#[derive(Clone, Debug)]
		pub struct RenderableCellExtra {
			pub zerowidth: Option<Vec<char>>,
			pub hyperlink: Option<Hyperlink>,
		}
	}
}

// Path is relative to this file's dir (alacritty_renderer/src/): up to the
// workspace root, then into the binary crate's renderer module. mod.rs's own
// submodules (rects/shader/text) resolve relative to mod.rs's real location.
#[path = "../../alacritty/src/renderer/mod.rs"]
pub mod renderer;

pub use renderer::Renderer;
